# This file 'organizes' the motors in any Dynamixel-based robot into meaningful units. The deployment will automatically install this file.
#
# Refer to http://emanual.robotis.com/#control-table to look up the control registers for the various motors.
#
# SETUP OF REGISTERS FOR THE INTERBOTIX PLATFORMS
#
# All registers were left to their default values except for the ones listed here:
#   1) ID............................The ID of the Dynamixel servo. Valid IDs range from 1 to 251.
#   2) Baud_Rate.....................The speed at which serial communication occurs. All motors have this set to 1M
#                                    baud (corresponds to a register value of '3')
#   3) Return_Delay_Time.............The amount of time the servo delays in sending a reply packet after receiving a
#                                    command packet. A value of '0' tells the servo to send a reply without any delay.
#   4) Drive_Mode:...................Used to define what direction is positive rotation. A value of '0' means CCW is
#                                    positive while a value of '1' means CW is positive. It also defines if profiles are
#                                    built based on velocity or time. 'Velocity' is the default (value of '0') and 'Time'
#                                    is a value of '4'. Adding the 'direction' value to the 'profile' value gives the
#                                    appropriate register value
#   5) Velocity_Limit................Defines the max speed of the motor. A value of '131' corresponds to a max speed
#                                    of PI rad/s. NOTE: this is only used in velocity control mode. I.e., has no effect
#                                    in the default position control setting.
#   6) Goal_Current..................Defines the goal current [0-Current_Limit] of the motor. Any value > 0 will cause
#                                    the motor to operate in current-based position control mode with the specified goal current.
#                                    This value must be less than or equal to Current_Limit. Look below for the conversion.
#                                    Only applicable to XM-series motors.
#   7) Current_Limit.................Defines the maximum current allowed [0-1193] of the motor.
#                                    This value must be greater than or equal to Goal_Current. The conversion for this
#                                    value is 2.69 mA. In other words, a maximum of ~3.2 A is possible.
#                                    Note that the effect of this value changes depending on the control mode and motor type.
#                                    Only XM-series motors officially have this register, so we will avoid writing it to the
#                                    XL-series ones. In position control mode, this value is unused. In current-based position
#                                    control mode, this value is used as the maximum current allowed. Since the Goal_Current
#                                    value is always less than or equal to this value, this value is generally unused as well.
#                                    What we do use this value for is to initiate a software-based error if the current of a
#                                    motor ever exceeds this value. Again, note that this should only ever happen under position
#                                    control mode since in current-based position control mode, the Goal_Current < Current_Limit.
#   8) Min_Position_Limit............Defines the minimum limit of a joint. Values range from 0 to 4095 with 2048
#                                    being equivalent to '0' rad and 0 being '-PI' rad.
#   9) Max_Position_Limit............Defines the maximum limit of a joint. Values range from 0 to 4095 with 2048
#                                    being equivalent to '0' rad and 4095 being 'PI' rad.
#  10) Secondary_ID..................If a joint is controlled by two motors (usually by the shoulder or elbow), one motor
#                                    can be set to follow the commands of another motor by setting this register to the ID
#                                    of the master. A value of '255' disables this.
#  11) Safety_Velocity_Limit.........Defines the max safety velocity limit [rad/s]. If the joint velocity ever violates
#                                    this limit, we override the current policy and attempt to slowly decelerate to a stop.
#                                    Note that the max speed of the WidowX is extremely high at 24.5 radians per second.
#                                    Only applicable to non-shadow motors. Shadow motors will use the same value as their
#                                    master motor. Note that this is NOT an official register defined by Dynamixel. Therefore,
#                                    we will avoid writing it to the register.
#
# Each motor's configs are grouped under the name of the joint the motor is controlling. The names are defined at
# http://support.interbotix.com/ under the 'Specifications' section. (Click a robot and scroll down to the 'Default Joint Limits' section.)

port: /dev/ttyDXL

joint_order: [ waist, shoulder, elbow, forearm_roll, wrist_angle, wrist_rotate, gripper ]
sleep_positions: [ 0, -1.80, 1.55, 0, 0.8, 0, 0 ]

joint_state_publisher:
  update_rate: 1000
  publish_states: true
  topic_name: joint_states

groups:
  arm: [ waist, shoulder, elbow, forearm_roll, wrist_angle, wrist_rotate, gripper ]

grippers:
  gripper:
    horn_radius: 0.014
    arm_length: 0.024
    left_finger: left_finger
    right_finger: right_finger

shadows:
  shoulder:
    shadow_list: [ shoulder_shadow ]
    calibrate: true
  elbow:
    shadow_list: [ elbow_shadow ]
    calibrate: true

sisters:

# Users can override this default value for goal current for all XM-motors.
goal_current: &goal_current_value 800

motors:
  waist:
    ID: 1
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 4
    Velocity_Limit: 131
    Goal_Current: *goal_current_value
    Current_Limit: 1193
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255
    Position_P_Gain: 400
    Position_D_Gain: 3
    Safety_Velocity_Limit: 2

  shoulder:
    ID: 2
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 4
    Velocity_Limit: 131
    Goal_Current: *goal_current_value
    Current_Limit: 1193
    Min_Position_Limit: 819
    Max_Position_Limit: 3345
    Secondary_ID: 255
    Position_P_Gain: 400
    Position_D_Gain: 3
    Safety_Velocity_Limit: 2

  shoulder_shadow:
    ID: 3
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 5
    Velocity_Limit: 131
    Goal_Current: *goal_current_value
    Current_Limit: 1193
    Min_Position_Limit: 819
    Max_Position_Limit: 3345
    Secondary_ID: 2
    Position_P_Gain: 400
    Position_D_Gain: 3

  elbow:
    ID: 4
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 4
    Velocity_Limit: 131
    Goal_Current: *goal_current_value
    Current_Limit: 1193
    Min_Position_Limit: 648
    Max_Position_Limit: 3094
    Secondary_ID: 255
    Position_P_Gain: 400
    Position_D_Gain: 3
    Safety_Velocity_Limit: 2

  elbow_shadow:
    ID: 5
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 5
    Velocity_Limit: 131
    Goal_Current: *goal_current_value
    Current_Limit: 1193
    Min_Position_Limit: 648
    Max_Position_Limit: 3094
    Secondary_ID: 4
    Position_P_Gain: 400
    Position_D_Gain: 3

  forearm_roll:
    ID: 6
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 4
    Velocity_Limit: 131
    Goal_Current: *goal_current_value
    Current_Limit: 1193
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255
    Position_P_Gain: 400
    Position_D_Gain: 3
    Safety_Velocity_Limit: 2

  wrist_angle:
    ID: 7
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 5
    Velocity_Limit: 131
    Goal_Current: *goal_current_value
    Current_Limit: 1193
    Min_Position_Limit: 910
    Max_Position_Limit: 3447
    Secondary_ID: 255
    Position_P_Gain: 400
    Position_D_Gain: 3
    Safety_Velocity_Limit: 2

# Note: everything below here is an XL-series motor.
  wrist_rotate:
    ID: 8
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 4
    Velocity_Limit: 131
    Current_Limit: 800
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255
    Position_P_Gain: 500
    Position_D_Gain: 0
    Safety_Velocity_Limit: 2

  gripper:
    ID: 9
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 4
    Velocity_Limit: 131
    Current_Limit: 1193
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255
    Position_P_Gain: 400
    Position_D_Gain: 0
    Safety_Velocity_Limit: 10
