name: build-xs-galactic

on:
  push:
    branches:
      - galactic
      - ros2-devel
  pull_request:
    branches:
      - galactic
      - ros2-devel
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  xs-galactic:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: galactic, ROS_REPO: main}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: src
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
